# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
