# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_confirm_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lastname',
        ),
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='year',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
