# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=20, null=True)),
                ('year', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accounts/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.RemoveField(
            model_name='account',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='account',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='year',
        ),
    ]
