# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171108_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fortune',
        ),
    ]
