# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20171123_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Uploaded image'),
        ),
    ]
